spring:
  application:
    name: eurekaserver
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      #     register to another server to achieve high availability
      defaultZone: http://${EUREKA2_ADDRESS}:8762/eureka/
    registerWithEureka: true
    fetchRegistry: true