spring:
  application:
    name: eurekaserver
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server01
    prefer-ip-address: true
  client:
    service-url:
      #     register to another server to achieve high availability
      defaultZone: http://eureka-server02:8762/eureka/
    registerWithEureka: true
    fetchRegistry: true