server:
  port: 8004
spring:
  application:
    name: url-link
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  shardingsphere:
    datasource:
      #datasource names
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://localhost:3306/url_account?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        type: com.zaxxer.hikari.HikariDataSource
        username: shorturl
        password: shorturl
    props:
      sql:
        show: true
    sharding:
      tables:
        link_group:
          key-generator:
            type: SNOWFLAKE
            column: id
            props:
              worker:
                id: ${workerId}
eureka:
  client:
    service-url:
      #     register to another server to achieve high availability
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
    fetch-registry: true

